server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  application:
    name: eureka-server
  profiles:
    active: local
    include:
      - app
      - db
      - file
  devtools:
    livereload:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  web:
    resources:
      add-mappings: false

---
# local
spring:
  config:
    activate:
      on-profile: local

---
# dev
spring:
  config:
    activate:
      on-profile: dev

---
# prd
spring:
  config:
    activate:
      on-profile: prd